//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comuns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comuns.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Você confirma a modificação do registro?.
        /// </summary>
        public static string MC01 {
            get {
                return ResourceManager.GetString("MC01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você confirma a exclusão do registro?.
        /// </summary>
        public static string MC02 {
            get {
                return ResourceManager.GetString("MC02", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se você cancelar a operação as modificações não serão salvas..
        /// </summary>
        public static string MC03 {
            get {
                return ResourceManager.GetString("MC03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você confirma a alteração de senha?.
        /// </summary>
        internal static string MC04 {
            get {
                return ResourceManager.GetString("MC04", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Inválida..
        /// </summary>
        public static string ME01 {
            get {
                return ResourceManager.GetString("ME01", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório Não Preenchido..
        /// </summary>
        public static string ME02 {
            get {
                return ResourceManager.GetString("ME02", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A {0} é Menor do que a Data Atual.
        /// </summary>
        public static string ME03 {
            get {
                return ResourceManager.GetString("ME03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no mínimo 8 digitos..
        /// </summary>
        internal static string ME04 {
            get {
                return ResourceManager.GetString("ME04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusão realizada com sucesso!.
        /// </summary>
        public static string MI01 {
            get {
                return ResourceManager.GetString("MI01", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alteração realizada com sucesso!.
        /// </summary>
        public static string MI02 {
            get {
                return ResourceManager.GetString("MI02", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclusão realizada com sucesso!.
        /// </summary>
        public static string MI03 {
            get {
                return ResourceManager.GetString("MI03", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro foi encontrado..
        /// </summary>
        public static string MI04 {
            get {
                return ResourceManager.GetString("MI04", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A quantidade desejada excede o limite disponível do produto!.
        /// </summary>
        public static string MI05 {
            get {
                return ResourceManager.GetString("MI05", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso!.
        /// </summary>
        public static string MI06 {
            get {
                return ResourceManager.GetString("MI06", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registro utilizado em outra tabela.
        /// </summary>
        public static string MI07 {
            get {
                return ResourceManager.GetString("MI07", resourceCulture);
            }
        }
    }
}
